import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { client } from "@/sanity/lib/client";
import { groq } from "next-sanity";
import Image from "next/image";
import urlFor from "./lib/urlFor";
import styles from "./page.module.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const query = groq`
  *[_type == "page"][0]{
    address,
    email,
    name,
    businessName,
    name,
    phone,
    logo
  }
`;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await client.fetch(query);
  const { phone, logo, name, email, address, businessName } = data as Global;
  console.log(logo);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav>
            {logo && (
              <Link href="/" className={styles.logoContain}>
                <Image src={urlFor(logo?.asset).url()} alt={logo?.alt} fill />
              </Link>
            )}
            <ul>
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/custom"}>Custom Garments</Link>
              </li>
              <li>
                <Link href={"/products"}>Products</Link>
              </li>
              <li>
                <Link href={"/alterations"}>Alterations</Link>
              </li>
              <li>
                <Link href={"/lessons"}>Sewing Lessons</Link>
              </li>
              <li>
                <Link href={"/contact"}>Contact</Link>
              </li>
            </ul>
          </nav>
          {children}
          <footer>
            <p>
              {name && name} | {email && email} | {phone && phone} |{" "}
              {address && address} |{" "}
              {businessName && `©${businessName}, all rights reserved.`}
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
